title: PXL Cloud | Demo Websites | Canva
email: happy@pxlcloud.co
phone: +12133285272
lmic: www.linkmalloc.com
image: https://pxlcloud.co/images/intro/new/hero.jpg
description: >- # this means to ignore newlines until "baseurl:"
  PXL Cloud Showcases what the web can do. Demo Websites you can choose from.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
